apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-kafka-deployment
spec:
  selector:
    matchLabels:
      app: worker-kafka
  replicas: 2
  template:
    metadata:
      labels:
        app: worker-kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: worker-kafka
        image: osmanpl9610/worker-kafka:latest
        
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-kafka
spec:
  selector:
    matchLabels:
      role: grpc-kafka
  replicas: 2
  template:
    metadata:
      labels:
        role: grpc-kafka
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: client-grpc-kafka
        image: osmanpl9610/client-grpc-kafka:latest
        ports:
        - containerPort: 4000
      - name: server-grpc-kafka
        image: osmanpl9610/server-grpc-kafka:latest
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-kafka-service
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    role: grpc-kafka